name: Kotlin CI with Gradle

on:
  push:
    paths:
      - '**.kt'
      - '**.kts'
      - '**/gradle.yml'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build --no-daemon

      - name: Execute Gradle test
        run: ./gradlew test --no-daemon